
spring:
#  profiles:
#    active: dev

  application:
    name: Journal App
  data:
    redis:
      uri: ${Redis_URI}
    mongodb:
      database: journaldb
      auto-index-creation: true
      uri: ${Mongo_URI}
  #      authentication-database: admin
  #      authentication-mechanism: SCRAM-SHA-256
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${G_Username}
    password: ${G_Password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#logging:
#  level:
#    net:
#      oceandepth:
#        journalApp: TRACE

weather:
  api:
    key: ${Weather_Key}

server:
  port: 8080
  servlet:
    context-path: /journal