
spring:
#  profiles:
#    active: dev

  application:
    name: Journal App
  data:
    redis:
      uri: redis://default:kalhoro@redis-16315.c264.ap-south-1-1.ec2.redns.redis-cloud.com:16315
    mongodb:
      database: journaldb
      auto-index-creation: true
      uri: mongodb+srv://hamid:kalhoro@cluster0.ev6lc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  #      authentication-database: admin
  #      authentication-mechanism: SCRAM-SHA-256
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hamidkalhoro.in@gmail.com
    password: vurn obwt ncdi pipe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#logging:
#  level:
#    net:
#      oceandepth:
#        journalApp: TRACE

weather:
  api:
    key: 6d16fd7350892af4daf0104c2138c7f8

server:
  port: 8080
  servlet:
    context-path: /journal